[package]
name = "db"
edition = "2021"
version = "0.1.0"

[dependencies]
dto = { path = "../dto" }

serde = { version = "1.0.219", features = ["derive"] }
futures = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
mongodb = "3.2.4"
dotenvy_macro = "0.15.7"
