# see https://github.com/vercel-community/rust/issues/87#issuecomment-1493528798
name: vercel-deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Vercel
        run: npm install --global vercel@latest
      - name: Install Tailwind CLI
        run: npm install --global tailwindcss @tailwindcss/cli
      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Pull Vercel Env File
        run: vercel env pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} .env
      # Generate WASM App with Trunk
      - name: Rust Setup App
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          default: true
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-binstall --locked
      - run: cargo binstall trunk -y
      - run: cargo binstall wasm-bindgen-cli -y
      - name: Build App
        run: trunk build --release --config app/Trunk.toml
      # Generate Functions with Vercel
      - name: Rust Setup Functions
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          default: true
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Functions
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # Deploy
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-args: "--prebuilt --archive=tgz --prod"
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ vars.VERCEL_ORG_ID }}
          vercel-project-id: ${{ vars.VERCEL_PROJECT_ID }}
